### ISSUE TITLE
Camera Id with docker

### ISSUE THREAD

**Issue by supertoto29** [sonia-auv/provider_vision#13]
**Warning :** Before creating an issue or task, make sure that it does not already exists in the [issue tracker](../). Thank you.

## Expected Behavior
Cam id should work in the code with docker

## Current Behavior
The camera id isn't the one expected with the docker container. It excepts a `int` as the camera id.

## Possible Solution
Code should be changed to adapt it to our neededs

## Comments
Some define that can be easily modify could do the trick

Id found
![image](https://user-images.githubusercontent.com/44241055/107896861-8ca3d980-6f05-11eb-8c34-88604e7f3249.png)

## Environment Used
- Project version : 0.1.1
- docker version : 19.03.6
- docker-compose version : 1.26.2

**Comment by supertoto29** [comment]
Instead of having the camera id, I get a string that has the parameter of the camera (idvendor & serial number)
![image](https://user-images.githubusercontent.com/44241055/107898544-f9b96e00-6f09-11eb-9257-eb68a8beb856.png)

**Comment by Kam0ss** [comment]
cam_ids should be something like 19208686, not USB\VID....

**Comment by supertoto29** [comment]
This screenshot has appear with the param for the cam id 19208686.

**Comment by supertoto29** [comment]
ID is fixed with a new function.
Only issue, when I started, I got some errors. I closed the container unplugged and replugged the cam and now the camera send data.

**Comment by supertoto29** [comment]
@Kam0ss I wanted to test the camera but the command
`
rqt_image_view
`
doesn't work in the container.

**Comment by supertoto29** [comment]
I am connected via ssh. So, I can't get a graphical display. It looks like with one camera it's working.

**Comment by supertoto29** [comment]
Waiting on input to confirm we are getting the image to close this issue.

**Comment by supertoto29** [comment]
This code gets the serial number from the data obtained in a docker container.
https://github.com/sonia-auv/provider_vision/blob/d0c49e4f6a8bf0598b99fd2f6d0eaa30c4c20cb5/src/camera.cpp#L323-L332

**Comment by Kam0ss** [comment]
> @Kam0ss I wanted to test the camera but the command
> `rqt_image_view`
> doesn't work in the container.

You can try to use a Xserver like XMing

**Comment by supertoto29** [comment]
Networking issue is causing that I can't see the image. Creating a new issues
