### ISSUE TITLE
Update to ROS Noetic

### ISSUE THREAD

**Issue by supertoto29** [sonia-auv/provider_vision#27]
**Warning :** Before creating an issue or task, make sure that it does not already exists in the [issue tracker](../). Thank you.

## Expected Behavior
Action should be working with noetic

## Current Behavior
Multiple package used by provider vision are for melodic.

## Possible Solution
Change the package in the docker compose file for noetic

## Environment Used
- Project version : 1.0.0
- docker version : 20.10.5
- docker-compose version : 1.28.5

**Comment by Kam0ss** [comment]
This issue is the reason PR #26 failed
