### ISSUE TITLE
Launch file not working

### ISSUE THREAD

**Issue by supertoto29** [sonia-auv/provider_vision#4]
## Expected Behavior
Launch of the provider with the roslaunch command

## Current Behavior
provider_vision.launch doesn't exist and can't be started

## Possible Solution
Change files name to suit the top folder name

## Environment Used
- Project version : 
- docker version : 
- docker-compose version :

**Comment by supertoto29** [comment]
@alexemdesgagne any ideas except the chmod +x

`ERROR: cannot launch node of type [provider_vision/provider_vision_node]: Cannot locate node of type [provider_vision_node] in package [provider_vision]. Make sure file exists in package path and permission is set to executable (chmod +x)`

**Comment by supertoto29** [comment]
@0x72D0 did you have a corrective for the previous error

**Comment by supertoto29** [comment]
now on Roslaunch error
`terminate called after throwing an instance of 'Spinnaker::Exception'
  what():  Spinnaker: System instance cannot be acquired. Could not load producer. Make sure that the environment variable FLIR_GENTL64_CTI exists, and points to the location of the file FLIR_GenTL.cti [-1012]`

**Comment by supertoto29** [comment]
To test with the camera

**Comment by supertoto29** [comment]
fixed with merge #6

**Comment by hiwind618** [comment]
> now on Roslaunch error
> `terminate called after throwing an instance of 'Spinnaker::Exception' what(): Spinnaker: System instance cannot be acquired. Could not load producer. Make sure that the environment variable FLIR_GENTL64_CTI exists, and points to the location of the file FLIR_GenTL.cti [-1012]`

have you solved this problem? I also have the problem.

**Comment by supertoto29** [comment]
@hiwind618 
We have manually created the env variables
https://github.com/sonia-auv/provider_vision/blob/520aad87f1d3665c432fb0aab6d495144fa577a7/Dockerfile#L42-L44
